name: LifeXP
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.0
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo.png"  # Ojo: respeta mayúsculas/minúsculas
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/Logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo.png
    - .env